journey:
  - state: intro
    message: "Hey there! Welcome to your coaching journey. When you're ready, type 'Next' to begin."
    next_state: waiting_for_happy

  - state: waiting_for_happy
    message: "Beautiful. Now, what is one meaningful goal you’d like to pursue over the next 6 months?"
    save_to: profile.happy_moments
    next_state: waiting_for_goal

  - state: waiting_for_goal
    message: "That's a great goal. What are 3 strengths you bring to the table to help you reach it?"
    save_to: profile.goal
    next_state: waiting_for_strengths

  - state: waiting_for_strengths
    message: "Noted. One last thing — what’s the biggest fear or blocker that could get in your way?"
    save_to: profile.strengths
    next_state: waiting_for_blocker

  - state: waiting_for_blocker
    message: "Thank you for being open. We're ready to move into daily coaching mode now. Type 'Next' to start Day 2!"
    save_to: profile.blocker
    next_state: ready
